# Generated by Django 4.2.2 on 2023-07-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_clientadditionaldetails_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysessions',
            name='cancelled_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
