# Generated by Django 4.2.2 on 2023-07-14 00:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('client.user',),
        ),
        migrations.CreateModel(
            name='TherapistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('session_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='therapist.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='TherapistAdditionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('hoursPerWeek', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), size=None)),
                ('technique', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), size=None)),
                ('describeYourSelf', models.CharField(blank=True, max_length=1000, null=True)),
                ('fluency', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), size=None)),
                ('chat2to3TimesADay', models.CharField(blank=True, max_length=100, null=True)),
                ('sessionPreferredTime', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('on-process', 'On Process'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('therapist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='therapist.therapist')),
            ],
        ),
    ]
