# Generated by Django 4.2.2 on 2023-07-14 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_therapysessions_cancelled_by_client'),
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistavailability',
            name='booked_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.therapysessions'),
        ),
    ]
